name: Run Tests and Generate Allure Report

on:
  push:
    branches: main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "v22.13.1"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
        continue-on-error: true

      - name: Generate Allure Report
        run: npm run report:allure:generate
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: reports
          commit_message: deploy allure report
