name: Run Tests and Generate Allure Report

on:
  push:
    branches: [docker]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t wdio-tests .

      - name: Run Tests and Generate Report in Docker
        run: docker run -v ${{ github.workspace }}/allure-report:/usr/src/app/allure-report wdio-tests

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: reports
          commit_message: deploy allure report
