name: Run Tests and Generate Allure Report

on:
  push:
    branches: [docker]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "v22.13.1"

      - name: Install dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t wdio-tests .

      - name: Clean old Allure results
        run: rm -rf allure-results allure-report

      - name: Run Tests and Generate Report in Docker
        run: docker run -v ${{ github.workspace }}/allure-results:/usr/src/app/allure-results wdio-tests
        continue-on-error: true

      - name: Generate Allure Report
        run: npm run report:allure:generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: reports
          commit_message: deploy allure report
